# -*- coding: utf-8 -*-
"""
editor_recognition.constants

集中存放识别/拟合相关的数值与策略常量，供各子模块共享。
"""

SCALE_RECALC_REL_TOL = 0.35
ANCHOR_PAIR_MIN_RATIO = 0.30
ANCHOR_PAIR_MIN_MATCHES = 2
ANCHOR_PAIR_MAX_SCALE = 6.0
SINGLE_ANCHOR_MIN_RATIO = 0.30
SINGLE_ANCHOR_MIN_MATCHES = 2
UNIQUE_RATIO_TOLERANCE = 0.30
UNIQUE_RATIO_MIN_REFERENCES = 2
UNIQUE_RATIO_MAX_RESIDUAL_PX = 48.0

FIT_STRATEGY_UNINITIALIZED = "uninitialized"
FIT_STRATEGY_ANCHOR_PAIR = "anchor_pair"
FIT_STRATEGY_SINGLE_ANCHOR = "single_anchor"
FIT_STRATEGY_GEOMETRY = "geometry_fit"
FIT_STRATEGY_UNIQUE_TITLE = "unique_title_translation"
FIT_STRATEGY_ORDINARY_NODES = "ordinary_nodes_position_match"
FIT_STRATEGY_RELATIVE_ANCHORS = "relative_anchor_alignment"
FIT_STRATEGY_ORIGIN_TRANSLATION = "origin_translation_voting"

ORDINARY_NODES_MIN_MATCHES = 2
ORDINARY_NODES_POSITION_TOLERANCE_MULTIPLIER = 1.5

RELATIVE_ANCHOR_MIN_MATCHES = 2
RELATIVE_ANCHOR_TOLERANCE_MULTIPLIER = 1.2
RELATIVE_ANCHOR_MAX_ANISOTROPY = 0.35
RELATIVE_ANCHOR_MIN_PROG_DELTA = 40.0
RELATIVE_ANCHOR_MAX_NEIGHBORS = 6

